import { BrainCircuit, TrendingUp, AlertTriangle, Clock } from "lucide-react";

const insights = [
  {
    icon: AlertTriangle,
    text: "18 critical complaints require immediate attention.",
  },
  {
    icon: TrendingUp,
    text: "Road-related complaints increased by 24% this week.",
  },
  {
    icon: Clock,
    text: "Average resolution time improved to 2.3 days.",
  },
];

const AIInsightsCard = () => {
  return (
    <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6">
      <div className="mb-6 flex items-center gap-3">
        <div className="rounded-xl bg-violet-500/20 p-3 text-violet-400">
          <BrainCircuit size={24} />
        </div>

        <div>
          <h2 className="text-xl font-semibold text-white">
            AI Insights
          </h2>

          <p className="text-sm text-slate-400">
            Smart recommendations generated by CivicMind AI
          </p>
        </div>
      </div>

      <div className="space-y-4">
        {insights.map((item, index) => {
          const Icon = item.icon;

          return (
            <div
              key={index}
              className="flex items-start gap-3 rounded-xl border border-slate-800 bg-slate-950/40 p-4"
            >
              <Icon
                size={20}
                className="mt-1 text-blue-400"
              />

              <p className="text-sm leading-6 text-slate-300">
                {item.text}
              </p>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default AIInsightsCard;