"""Add complaint category

Revision ID: 234ce869158b
Revises: 4737ffc47e68
Create Date: 2026-07-26 08:54:28.668896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234ce869158b'
down_revision: Union[str, Sequence[str], None] = '4737ffc47e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "complaints",
        sa.Column(
            "category",
            sa.String(length=100),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE complaints SET category = 'General' WHERE category IS NULL"
    )

    op.alter_column(
        "complaints",
        "category",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'category')
    # ### end Alembic commands ###
