"""add ai fields to complaints

Revision ID: 4737ffc47e68
Revises: fb0e54283d77
Create Date: 2026-07-23 14:19:05.865510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4737ffc47e68'
down_revision: Union[str, Sequence[str], None] = 'fb0e54283d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('ai_detected_issue', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('ai_recommended_department', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('ai_estimated_cost', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('ai_analysis_status', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'ai_analysis_status')
    op.drop_column('complaints', 'ai_estimated_cost')
    op.drop_column('complaints', 'ai_recommended_department')
    op.drop_column('complaints', 'ai_confidence')
    op.drop_column('complaints', 'ai_detected_issue')
    # ### end Alembic commands ###
