"""Add complaint assignment fields

Revision ID: a0e25dd20bcb
Revises: 2e5754c648ec
Create Date: 2026-07-20 12:26:40.571228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e25dd20bcb'
down_revision: Union[str, Sequence[str], None] = '2e5754c648ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('assigned_department_id', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('assigned_officer_id', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.add_column('complaints', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('complaints', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'complaints', 'users', ['assigned_officer_id'], ['id'])
    op.create_foreign_key(None, 'complaints', 'departments', ['assigned_department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'resolved_at')
    op.drop_column('complaints', 'started_at')
    op.drop_column('complaints', 'assigned_at')
    op.drop_column('complaints', 'assigned_officer_id')
    op.drop_column('complaints', 'assigned_department_id')
    # ### end Alembic commands ###
