"""create complaint_history table

Revision ID: b99ebc1f2798
Revises: 87daa3cbdf8d
Create Date: 2026-07-23 10:53:47.411651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99ebc1f2798'
down_revision: Union[str, Sequence[str], None] = '87daa3cbdf8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "complaint_history",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),

        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),

        sa.Column(
            "complaint_id",
            sa.Integer(),
            sa.ForeignKey("complaints.id"),
            nullable=False,
        ),

        sa.Column(
            "performed_by",
            sa.Integer(),
            sa.ForeignKey("users.id"),
            nullable=False,
        ),

        sa.Column(
            "action",
            sa.String(length=100),
            nullable=False,
        ),

        sa.Column(
            "old_status",
            sa.String(length=50),
            nullable=True,
        ),

        sa.Column(
            "new_status",
            sa.String(length=50),
            nullable=True,
        ),

        sa.Column(
            "remarks",
            sa.Text(),
            nullable=True,
        ),
    )


def downgrade() -> None:
    op.drop_table("complaint_history")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
