"""add ai fields to complaint

Revision ID: fb0e54283d77
Revises: b99ebc1f2798
Create Date: 2026-07-23 13:21:46.553547

"""

'''from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb0e54283d77'
down_revision: Union[str, Sequence[str], None] = 'b99ebc1f2798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "complaints",
        sa.Column("ai_detected_issue", sa.String(length=100), nullable=True),
    )

    op.add_column(
        "complaints",
        sa.Column("ai_confidence", sa.Float(), nullable=True),
    )

    op.add_column(
        "complaints",
        sa.Column("ai_estimated_cost", sa.Integer(), nullable=True),
    )

    op.add_column(
        "complaints",
        sa.Column("ai_recommended_department", sa.String(length=100), nullable=True),
    )

    op.add_column(
        "complaints",
        sa.Column("ai_analysis_status", sa.String(length=30), nullable=True),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('complaint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('old_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('new_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name='complaint_history_complaint_id_fkey'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name='complaint_history_performed_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='complaint_history_pkey')
    )
    # ### end Alembic commands ###
'''

"""add ai fields to complaint

Revision ID: fb0e54283d77
Revises: b99ebc1f2798
Create Date: 2026-07-23 13:21:46.553547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fb0e54283d77"
down_revision: Union[str, Sequence[str], None] = "b99ebc1f2798"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass